# Generated by Django 3.2.3 on 2022-06-12 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_note_languange_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='languange_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.languangedetails', verbose_name='Programming Language'),
        ),
    ]
